

export const allCountries = [
    { code: 'AD', label: 'Andorra', phone: '376', mobileNoLength: 10 },
    { code: 'AE', label: 'United Arab Emirates', phone: '971', mobileNoLength: 9 },
    { code: 'AF', label: 'Afghanistan', phone: '93', mobileNoLength: 9 },
    { code: 'AG', label: 'Antigua and Barbuda', phone: '1-268', mobileNoLength: 10 },
    { code: 'AI', label: 'Anguilla', phone: '1-264', mobileNoLength: 10 },
    { code: 'AL', label: 'Albania', phone: '355', mobileNoLength: 9 },
    { code: 'AM', label: 'Armenia', phone: '374', mobileNoLength: 8 },
    { code: 'AO', label: 'Angola', phone: '244', mobileNoLength: 9 },
    { code: 'AQ', label: 'Antarctica', phone: '672', mobileNoLength: null },
    { code: 'AR', label: 'Argentina', phone: '54', mobileNoLength: 10 },
    { code: 'AS', label: 'American Samoa', phone: '1-684', mobileNoLength: 10 },
    { code: 'AT', label: 'Austria', phone: '43', mobileNoLength: 10 },
    { code: 'AU', label: 'Australia', phone: '61', mobileNoLength: 9 },
    { code: 'AW', label: 'Aruba', phone: '297', mobileNoLength: 7 },
    { code: 'AX', label: 'Alland Islands', phone: '358', mobileNoLength: 7 },
    { code: 'AZ', label: 'Azerbaijan', phone: '994', mobileNoLength: 9 },
    { code: 'BA', label: 'Bosnia and Herzegovina', phone: '387', mobileNoLength: 8 },
    { code: 'BH', label: 'Bahrain', phone: '973', mobileNoLength: 8 },
    { code: 'BB', label: 'Barbados', phone: '1-246', mobileNoLength: 7 },
    { code: 'BD', label: 'Bangladesh', phone: '880', mobileNoLength: 10 },
    { code: 'BE', label: 'Belgium', phone: '32', mobileNoLength: 9 },
    { code: 'BF', label: 'Burkina Faso', phone: '226', mobileNoLength: 8 },
    { code: 'BG', label: 'Bulgaria', phone: '359', mobileNoLength: 9 },
    { code: 'BI', label: 'Burundi', phone: '257', mobileNoLength: 8 },
    { code: 'BJ', label: 'Benin', phone: '229', mobileNoLength: 8 },    
    { code: 'BL', label: 'Saint Barthelemy', phone: '590', mobileNoLength: 9 },
    { code: 'BM', label: 'Bermuda', phone: '1-441', mobileNoLength: 7 },
    { code: 'BN', label: 'Brunei Darussalam', phone: '673', mobileNoLength: 7 },
    { code: 'BO', label: 'Bolivia', phone: '591', mobileNoLength: 8 },
    { code: 'BR', label: 'Brazil', phone: '55', mobileNoLength: 11 },
    { code: 'BS', label: 'Bahamas', phone: '1-242', mobileNoLength: 7 },
    { code: 'BT', label: 'Bhutan', phone: '975', mobileNoLength: 8 },
    { code: 'BV', label: 'Bouvet Island', phone: '47', mobileNoLength: null },
    { code: 'BW', label: 'Botswana', phone: '267', mobileNoLength: 8 },
    { code: 'BY', label: 'Belarus', phone: '375', mobileNoLength: 9 },
    { code: 'BZ', label: 'Belize', phone: '501', mobileNoLength: 7 },
    { code: 'CA', label: 'Canada', phone: '1', mobileNoLength: 10 },
    { code: 'CC', label: 'Cocos (Keeling) Islands', phone: '61', mobileNoLength: 9 },
    { code: 'CD', label: 'Congo, Democratic Republic of the', phone: '243', mobileNoLength: 9 },
    { code: 'CF', label: 'Central African Republic', phone: '236', mobileNoLength: 7 },
    { code: 'CG', label: 'Congo, Republic of the', phone: '242', mobileNoLength: 7 },
    { code: 'CH', label: 'Switzerland', phone: '41', mobileNoLength: 9 },
    { code: 'CI', label: "Cote d'Ivoire", phone: '225', mobileNoLength: 8 },
    { code: 'CK', label: 'Cook Islands', phone: '682', mobileNoLength: 5 },
    { code: 'CL', label: 'Chile', phone: '56', mobileNoLength: 9 },
    { code: 'CM', label: 'Cameroon', phone: '237', mobileNoLength: 9 },
    { code: 'CN', label: 'China', phone: '86', mobileNoLength: 11 },
    { code: 'CO', label: 'Colombia', phone: '57', mobileNoLength: 10 },
    { code: 'CR', label: 'Costa Rica', phone: '506', mobileNoLength: 8 },
    { code: 'CU', label: 'Cuba', phone: '53', mobileNoLength: 8 },
    { code: 'CV', label: 'Cape Verde', phone: '238', mobileNoLength: 7 },
    { code: 'CW', label: 'Curacao', phone: '599', mobileNoLength: 7 },
    { code: 'CX', label: 'Christmas Island', phone: '61', mobileNoLength: 9 },
    { code: 'CY', label: 'Cyprus', phone: '357', mobileNoLength: 8 },
    { code: 'CZ', label: 'Czech Republic', phone: '420', mobileNoLength: 9 },
    { code: 'DE', label: 'Germany', phone: '49', mobileNoLength: 11 },
    { code: 'DJ', label: 'Djibouti', phone: '253', mobileNoLength: 8 },
    { code: 'DK', label: 'Denmark', phone: '45', mobileNoLength: 8 },
    { code: 'DM', label: 'Dominica', phone: '1-767', mobileNoLength: 7 },
    { code: 'DO', label: 'Dominican Republic', phone: '1-809', mobileNoLength: 10 },
    { code: 'DZ', label: 'Algeria', phone: '213', mobileNoLength: 9 },
    { code: 'EC', label: 'Ecuador', phone: '593', mobileNoLength: 9 },
    { code: 'EE', label: 'Estonia', phone: '372', mobileNoLength: 7 },
    { code: 'EG', label: 'Egypt', phone: '20', mobileNoLength: 10 },
    { code: 'EH', label: 'Western Sahara', phone: '212', mobileNoLength: 9 },
    { code: 'ER', label: 'Eritrea', phone: '291', mobileNoLength: 7 },
    { code: 'ES', label: 'Spain', phone: '34', mobileNoLength: 9 },
    { code: 'ET', label: 'Ethiopia', phone: '251', mobileNoLength: 9 },
    { code: 'FI', label: 'Finland', phone: '358', mobileNoLength: 9 },
    { code: 'FJ', label: 'Fiji', phone: '679', mobileNoLength: 7 },
    { code: 'FK', label: 'Falkland Islands (Malvinas)', phone: '500', mobileNoLength: 5 },
    { code: 'FM', label: 'Micronesia, Federated States of', phone: '691', mobileNoLength: 7 },
    { code: 'FO', label: 'Faroe Islands', phone: '298', mobileNoLength: 6 },
    { code: 'FR', label: 'France', phone: '33', mobileNoLength: 9 },
    { code: 'GA', label: 'Gabon', phone: '241', mobileNoLength: 8 },
    { code: 'GB', label: 'United Kingdom', phone: '44', mobileNoLength: 10 },
    { code: 'GD', label: 'Grenada', phone: '1-473', mobileNoLength: 7 },
    { code: 'GE', label: 'Georgia', phone: '995', mobileNoLength: 9 },
    { code: 'GF', label: 'French Guiana', phone: '594', mobileNoLength: 9 },
    { code: 'GG', label: 'Guernsey', phone: '44', mobileNoLength: 10 },
    { code: 'GH', label: 'Ghana', phone: '233', mobileNoLength: 9 },
    { code: 'GI', label: 'Gibraltar', phone: '350', mobileNoLength: 8 },
    { code: 'GL', label: 'Greenland', phone: '299', mobileNoLength: 6 },
    { code: 'GM', label: 'Gambia', phone: '220', mobileNoLength: 7 },
    { code: 'GN', label: 'Guinea', phone: '224', mobileNoLength: 8 },
    { code: 'GP', label: 'Guadeloupe', phone: '590', mobileNoLength: 9 },
    { code: 'GQ', label: 'Equatorial Guinea', phone: '240', mobileNoLength: 9 },
    { code: 'GR', label: 'Greece', phone: '30', mobileNoLength: 10 },
    { code: 'GS', label: 'South Georgia and the South Sandwich Islands', phone: '500', mobileNoLength: null },
    { code: 'GT', label: 'Guatemala', phone: '502', mobileNoLength: 8 },
    { code: 'GU', label: 'Guam', phone: '1-671', mobileNoLength: 10 },
    { code: 'GW', label: 'Guinea-Bissau', phone: '245', mobileNoLength: 7 },
    { code: 'GY', label: 'Guyana', phone: '592', mobileNoLength: 7 },
    { code: 'HK', label: 'Hong Kong', phone: '852', mobileNoLength: 8 },
    { code: 'HM', label: 'Heard Island and McDonald Islands', phone: '672', mobileNoLength: null },
    { code: 'HN', label: 'Honduras', phone: '504', mobileNoLength: 8 },
    { code: 'HR', label: 'Croatia', phone: '385', mobileNoLength: 9 },
    { code: 'HT', label: 'Haiti', phone: '509', mobileNoLength: 8 },
    { code: 'HU', label: 'Hungary', phone: '36', mobileNoLength: 9 },
    { code: 'ID', label: 'Indonesia', phone: '62', mobileNoLength: 11 },
    { code: 'IE', label: 'Ireland', phone: '353', mobileNoLength: 9 },
    { code: 'IL', label: 'Israel', phone: '972', mobileNoLength: 9 },
    { code: 'IM', label: 'Isle of Man', phone: '44', mobileNoLength: 10 },
    { code: 'IN', label: 'India', phone: '91', mobileNoLength: 10 },
    { code: 'IO', label: 'British Indian Ocean Territory', phone: '246', mobileNoLength: 7 },
    { code: 'IQ', label: 'Iraq', phone: '964', mobileNoLength: 10 },
    { code: 'IR', label: 'Iran, Islamic Republic of', phone: '98', mobileNoLength: 10 },
    { code: 'IS', label: 'Iceland', phone: '354', mobileNoLength: 7 },
    { code: 'IT', label: 'Italy', phone: '39', mobileNoLength: 10 },
    { code: 'JE', label: 'Jersey', phone: '44', mobileNoLength: 10 },
    { code: 'JM', label: 'Jamaica', phone: '1-876', mobileNoLength: 7 },
    { code: 'JO', label: 'Jordan', phone: '962', mobileNoLength: 9 },
    { code: 'JP', label: 'Japan', phone: '81', mobileNoLength: 10 },
    { code: 'KE', label: 'Kenya', phone: '254', mobileNoLength: 9 },
    { code: 'KG', label: 'Kyrgyzstan', phone: '996', mobileNoLength: 9 },
    { code: 'KW', label: 'Kuwait', phone: '965', mobileNoLength: 8 },
    { code: 'KH', label: 'Cambodia', phone: '855', mobileNoLength: 9 },
    { code: 'KI', label: 'Kiribati', phone: '686', mobileNoLength: 5 },
    { code: 'KM', label: 'Comoros', phone: '269', mobileNoLength: 7 },
    { code: 'KN', label: 'Saint Kitts and Nevis', phone: '1-869', mobileNoLength: 10 },
    { code: 'KP', label: "Korea, Democratic People's Republic of", phone: '850', mobileNoLength: 9 },
    { code: 'KR', label: 'Korea, Republic of', phone: '82', mobileNoLength: 10 },
    { code: 'KY', label: 'Cayman Islands', phone: '1-345', mobileNoLength: 10 },
    { code: 'KZ', label: 'Kazakhstan', phone: '7', mobileNoLength: 10 },
    { code: 'LA', label: "Lao People's Democratic Republic", phone: '856', mobileNoLength: 9 },
    { code: 'LB', label: 'Lebanon', phone: '961', mobileNoLength: 8 },
    { code: 'LC', label: 'Saint Lucia', phone: '1-758', mobileNoLength: 7 },
    { code: 'LI', label: 'Liechtenstein', phone: '423', mobileNoLength: 7 },
    { code: 'LK', label: 'Sri Lanka', phone: '94', mobileNoLength: 9 },
    { code: 'LR', label: 'Liberia', phone: '231', mobileNoLength: 7 },
    { code: 'LS', label: 'Lesotho', phone: '266', mobileNoLength: 8 },
    { code: 'LT', label: 'Lithuania', phone: '370', mobileNoLength: 8 },
    { code: 'LU', label: 'Luxembourg', phone: '352', mobileNoLength: 9 },
    { code: 'LV', label: 'Latvia', phone: '371', mobileNoLength: 8 },
    { code: 'LY', label: 'Libya', phone: '218', mobileNoLength: 9 },
    { code: 'MA', label: 'Morocco', phone: '212', mobileNoLength: 9 },
    { code: 'MC', label: 'Monaco', phone: '377', mobileNoLength: 9 },
    { code: 'MD', label: 'Moldova, Republic of', phone: '373', mobileNoLength: 8 },
    { code: 'ME', label: 'Montenegro', phone: '382', mobileNoLength: 8 },
    { code: 'MF', label: 'Saint Martin (French part)', phone: '590', mobileNoLength: 9 },
    { code: 'MG', label: 'Madagascar', phone: '261', mobileNoLength: 9 },
    { code: 'MH', label: 'Marshall Islands', phone: '692', mobileNoLength: 7 },
    { code: 'MK', label: 'Macedonia, the Former Yugoslav Republic of', phone: '389', mobileNoLength: 8 },
    { code: 'ML', label: 'Mali', phone: '223', mobileNoLength: 8 },
    { code: 'MM', label: 'Myanmar', phone: '95', mobileNoLength: 9 },
    { code: 'MN', label: 'Mongolia', phone: '976', mobileNoLength: 8 },
    { code: 'MO', label: 'Macao', phone: '853', mobileNoLength: 8 },
    { code: 'MP', label: 'Northern Mariana Islands', phone: '1-670', mobileNoLength: 10 },
    { code: 'MQ', label: 'Martinique', phone: '596', mobileNoLength: 9 },
    { code: 'MR', label: 'Mauritania', phone: '222', mobileNoLength: 8 },
    { code: 'MS', label: 'Montserrat', phone: '1-664', mobileNoLength: 7 },
    { code: 'MT', label: 'Malta', phone: '356', mobileNoLength: 8 },
    { code: 'MU', label: 'Mauritius', phone: '230', mobileNoLength: 7 },
    { code: 'MV', label: 'Maldives', phone: '960', mobileNoLength: 7 },
    { code: 'MW', label: 'Malawi', phone: '265', mobileNoLength: 9 },
    { code: 'MX', label: 'Mexico', phone: '52', mobileNoLength: 10 },
    { code: 'MY', label: 'Malaysia', phone: '60', mobileNoLength: 10 },
    { code: 'MZ', label: 'Mozambique', phone: '258', mobileNoLength: 9 },
    { code: 'NA', label: 'Namibia', phone: '264', mobileNoLength: 8 },
    { code: 'NC', label: 'New Caledonia', phone: '687', mobileNoLength: 6 },
    { code: 'NE', label: 'Niger', phone: '227', mobileNoLength: 8 },
    { code: 'NF', label: 'Norfolk Island', phone: '672', mobileNoLength: null },
    { code: 'NG', label: 'Nigeria', phone: '234', mobileNoLength: 10 },
    { code: 'NI', label: 'Nicaragua', phone: '505', mobileNoLength: 8 },
    { code: 'NL', label: 'Netherlands', phone: '31', mobileNoLength: 10 },
    { code: 'NO', label: 'Norway', phone: '47', mobileNoLength: 8 },
    { code: 'QA', label: 'Qatar', phone: '974', mobileNoLength: 8 },
    { code: 'NP', label: 'Nepal', phone: '977', mobileNoLength: 10 },
    { code: 'NR', label: 'Nauru', phone: '674', mobileNoLength: 7 },
    { code: 'NU', label: 'Niue', phone: '683', mobileNoLength: 4 },
    { code: 'NZ', label: 'New Zealand', phone: '64', mobileNoLength: 10 },
    { code: 'OM', label: 'Oman', phone: '968', mobileNoLength: 8 },
    { code: 'PA', label: 'Panama', phone: '507', mobileNoLength: 8 },
    { code: 'PE', label: 'Peru', phone: '51', mobileNoLength: 9 },
    { code: 'PF', label: 'French Polynesia', phone: '689', mobileNoLength: 6 },
    { code: 'PG', label: 'Papua New Guinea', phone: '675', mobileNoLength: 7 },
    { code: 'PH', label: 'Philippines', phone: '63', mobileNoLength: 10 },
    { code: 'PK', label: 'Pakistan', phone: '92', mobileNoLength: 10 },
    { code: 'PL', label: 'Poland', phone: '48', mobileNoLength: 9 },
    { code: 'PM', label: 'Saint Pierre and Miquelon', phone: '508', mobileNoLength: 6 },
    { code: 'PN', label: 'Pitcairn', phone: '870', mobileNoLength: 5 },
    { code: 'PR', label: 'Puerto Rico', phone: '1', mobileNoLength: 10 },
    { code: 'PS', label: 'Palestine, State of', phone: '970', mobileNoLength: 9 },
    { code: 'PT', label: 'Portugal', phone: '351', mobileNoLength: 9 },
    { code: 'PW', label: 'Palau', phone: '680', mobileNoLength: 7 },
    { code: 'PY', label: 'Paraguay', phone: '595', mobileNoLength: 9 },
    { code: 'RE', label: 'Reunion', phone: '262', mobileNoLength: 9 },
    { code: 'RO', label: 'Romania', phone: '40', mobileNoLength: 9 },
    { code: 'RS', label: 'Serbia', phone: '381', mobileNoLength: 9 },
    { code: 'RU', label: 'Russian Federation', phone: '7', mobileNoLength: 10 },
    { code: 'RW', label: 'Rwanda', phone: '250', mobileNoLength: 9 },
    { code: 'SB', label: 'Solomon Islands', phone: '677', mobileNoLength: 7 },
    { code: 'SC', label: 'Seychelles', phone: '248', mobileNoLength: 7 },
    { code: 'SD', label: 'Sudan', phone: '249', mobileNoLength: 9 },
    { code: 'SE', label: 'Sweden', phone: '46', mobileNoLength: 10 },
    { code: 'SG', label: 'Singapore', phone: '65', mobileNoLength: 8 },
    { code: 'SH', label: 'Saint Helena', phone: '290', mobileNoLength: 4 },
    { code: 'SI', label: 'Slovenia', phone: '386', mobileNoLength: 8 },
    { code: 'SJ', label: 'Svalbard and Jan Mayen', phone: '47', mobileNoLength: null },
    { code: 'SK', label: 'Slovakia', phone: '421', mobileNoLength: 9 },
    { code: 'SL', label: 'Sierra Leone', phone: '232', mobileNoLength: 8 },
    { code: 'SM', label: 'San Marino', phone: '378', mobileNoLength: 10 },
    { code: 'SN', label: 'Senegal', phone: '221', mobileNoLength: 9 },
    { code: 'SO', label: 'Somalia', phone: '252', mobileNoLength: 8 },
    { code: 'SR', label: 'Suriname', phone: '597', mobileNoLength: 7 },
    { code: 'SS', label: 'South Sudan', phone: '211', mobileNoLength: 9 },
    { code: 'ST', label: 'Sao Tome and Principe', phone: '239', mobileNoLength: 7 },
    { code: 'SV', label: 'El Salvador', phone: '503', mobileNoLength: 8 },
    { code: 'SX', label: 'Sint Maarten (Dutch part)', phone: '1-721', mobileNoLength: 10 },
    { code: 'SY', label: 'Syrian Arab Republic', phone: '963', mobileNoLength: 9 },
    { code: 'SZ', label: 'Swaziland', phone: '268', mobileNoLength: 8 },
    { code: 'TC', label: 'Turks and Caicos Islands', phone: '1-649', mobileNoLength: 10 },
    { code: 'TD', label: 'Chad', phone: '235', mobileNoLength: 8 },
    { code: 'TF', label: 'French Southern Territories', phone: '262', mobileNoLength: null },
    { code: 'TG', label: 'Togo', phone: '228', mobileNoLength: 8 },
    { code: 'TH', label: 'Thailand', phone: '66', mobileNoLength: 9 },
    { code: 'TJ', label: 'Tajikistan', phone: '992', mobileNoLength: 9 },
    { code: 'TK', label: 'Tokelau', phone: '690', mobileNoLength: 4 },
    { code: 'TL', label: 'Timor-Leste', phone: '670', mobileNoLength: 7 },
    { code: 'TM', label: 'Turkmenistan', phone: '993', mobileNoLength: 8 },
    { code: 'TN', label: 'Tunisia', phone: '216', mobileNoLength: 8 },
    { code: 'TO', label: 'Tonga', phone: '676', mobileNoLength: 5 },
    { code: 'TR', label: 'Turkey', phone: '90', mobileNoLength: 10 },
    { code: 'TT', label: 'Trinidad and Tobago', phone: '1-868', mobileNoLength: 7 },
    { code: 'TV', label: 'Tuvalu', phone: '688', mobileNoLength: 5 },
    { code: 'TW', label: 'Taiwan, Province of China', phone: '886', mobileNoLength: 9 },
    { code: 'TZ', label: 'Tanzania, United Republic of', phone: '255', mobileNoLength: 9 },
    { code: 'UA', label: 'Ukraine', phone: '380', mobileNoLength: 9 },
    { code: 'UG', label: 'Uganda', phone: '256', mobileNoLength: 9 },
    { code: 'UM', label: 'United States Minor Outlying Islands', phone: '1', mobileNoLength: null },
    { code: 'US', label: 'United States', phone: '1', mobileNoLength: 10 },
    { code: 'UY', label: 'Uruguay', phone: '598', mobileNoLength: 8 },
    { code: 'UZ', label: 'Uzbekistan', phone: '998', mobileNoLength: 9 },
    { code: 'VA', label: 'Holy See (Vatican City State)', phone: '379', mobileNoLength: null },
    { code: 'VC', label: 'Saint Vincent and the Grenadines', phone: '1-784', mobileNoLength: 7 },
    { code: 'SA', label: 'Saudi Arabia', phone: '966', mobileNoLength: 9 },
    { code: 'VE', label: 'Venezuela', phone: '58', mobileNoLength: 10 },
    { code: 'VG', label: 'Virgin Islands, British', phone: '1-284', mobileNoLength: 10 },
    { code: 'VI', label: 'Virgin Islands, U.S.', phone: '1-340', mobileNoLength: 10 },
    { code: 'VN', label: 'Vietnam', phone: '84', mobileNoLength: 10 },
    { code: 'VU', label: 'Vanuatu', phone: '678', mobileNoLength: 7 },
    { code: 'WF', label: 'Wallis and Futuna', phone: '681', mobileNoLength: 6 },
    { code: 'WS', label: 'Samoa', phone: '685', mobileNoLength: 7 },
    { code: 'YE', label: 'Yemen', phone: '967', mobileNoLength: 9 },
    { code: 'YT', label: 'Mayotte', phone: '262', mobileNoLength: 9 },
    { code: 'ZA', label: 'South Africa', phone: '27', mobileNoLength: 9 },
    { code: 'ZM', label: 'Zambia', phone: '260', mobileNoLength: 9 },
    { code: 'ZW', label: 'Zimbabwe', phone: '263', mobileNoLength: 9 }
];


// export const countries = [
//     { code: 'AE', label: 'United Arab Emirates', phone: '971', mobileNoLength: 9 },
//     { code: 'OM', label: 'Oman', phone: '968', mobileNoLength: 8 },
//     { code: 'BH', label: 'Bahrain', phone: '973', mobileNoLength: 8 },
//     { code: 'QA', label: 'Qatar', phone: '974', mobileNoLength: 8 },
//     { code: 'KW', label: 'Kuwait', phone: '965', mobileNoLength: 8 },
//     { code: 'SA', label: 'Saudi Arabia', phone: '966', mobileNoLength: 9 },
// ]